name: Build & Publish Unstable Docker Image

on:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: fachschaftmathphysinfo/kummerkasten
  REGISTRY: ghcr.io

jobs:
  unstable:
    runs-on: ubuntu-latest
    name: Build & Push “unstable” Tag


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & tag as unstable
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE:unstable .

      - name: Push unstable tag
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push $IMAGE:unstable

